allow-lan: true
bind-address: 0.0.0.0
mode: rule
log-level: error
ipv6: false
external-controller: 0.0.0.0:9090
secret: bagus
external-ui: ui
unified-delay: true
tcp-concurrent: true
dns:
  enable: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - https://cloudflare-dns.com/dns-query
  - 1.1.1.1
port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 7893
tproxy-port: 7894
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  mtu: 1500
proxies:
- name: Server
  type: vless
  server: quiz.vidio.com
  port: 80
  udp: true
  uuid: e993dc08-05f4-48eb-b9ee-bce7aabe1112
  packet-encoding: xudp
  tls: false
  alpn:
  - http/1.1
  network: ws
  ws-opts:
    path: /146.235.18.248:45137
    headers:
      host: cf.bagusfast.workers.dev
proxy-groups:
- name: Bagus
  type: select
  proxies:
  - Ping Server
- name: Ping Server
  type: url-test
  url: http://quiz.vidio.com
  interval: 180
  tolerance: 100
  proxies:
  - Server
rules:
- IP-CIDR,104.22.4.240/32,DIRECT
- IP-CIDR,104.22.5.240/32,DIRECT
- IP-CIDR,172.67.5.14/32,DIRECT
- MATCH,Bagus
