allow-lan: true
bind-address: 0.0.0.0
mode: rule
log-level: error
ipv6: false
external-controller: 0.0.0.0:9090
secret: bagus
external-ui: ui
unified-delay: true
tcp-concurrent: true
dns:
  enable: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - system
port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 7893
tproxy-port: 7894
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  mtu: 1500
proxies:
- name: Server 1
  type: vless
  server: 104.22.4.240
  port: 80
  udp: true
  uuid: e993dc08-05f4-48eb-b9ee-bce7aabe1112
  packet-encoding: xudp
  tls: false
  alpn:
  - http/1.1
  network: ws
  ws-opts:
    path: /146.235.18.248:45137
    headers:
      host: cf.bagusfast.workers.dev
- name: Server 2
  type: vless
  server: 104.17.156.243
  port: 80
  udp: true
  uuid: e993dc08-05f4-48eb-b9ee-bce7aabe1112
  packet-encoding: xudp
  tls: false
  alpn:
  - http/1.1
  network: ws
  ws-opts:
    path: /146.235.18.248:45137
    headers:
      host: cf.bagusfast.workers.dev
- name: Server 3
  type: vless
  server: 104.17.157.243
  port: 80
  udp: true
  uuid: e993dc08-05f4-48eb-b9ee-bce7aabe1112
  packet-encoding: xudp
  tls: false
  alpn:
  - http/1.1
  network: ws
  ws-opts:
    path: /146.235.18.248:45137
    headers:
      host: cf.bagusfast.workers.dev
- name: Server 4
  type: vless
  server: 104.17.158.243
  port: 80
  udp: true
  uuid: e993dc08-05f4-48eb-b9ee-bce7aabe1112
  packet-encoding: xudp
  tls: false
  alpn:
  - http/1.1
  network: ws
  ws-opts:
    path: /146.235.18.248:45137
    headers:
      host: cf.bagusfast.workers.dev
- name: Server 5
  type: vless
  server: 104.17.159.243
  port: 80
  udp: true
  uuid: e993dc08-05f4-48eb-b9ee-bce7aabe1112
  packet-encoding: xudp
  tls: false
  alpn:
  - http/1.1
  network: ws
  ws-opts:
    path: /146.235.18.248:45137
    headers:
      host: cf.bagusfast.workers.dev
- name: Server 6
  type: vless
  server: 104.22.4.240
  port: 80
  udp: true
  uuid: e993dc08-05f4-48eb-b9ee-bce7aabe1112
  packet-encoding: xudp
  tls: false
  alpn:
  - http/1.1
  network: ws
  ws-opts:
    path: /146.235.18.248:45137
    headers:
      host: cf.bagusfast.workers.dev
- name: Server 7
  type: vless
  server: 104.22.5.240
  port: 80
  udp: true
  uuid: e993dc08-05f4-48eb-b9ee-bce7aabe1112
  packet-encoding: xudp
  tls: false
  alpn:
  - http/1.1
  network: ws
  ws-opts:
    path: /146.235.18.248:45137
    headers:
      host: cf.bagusfast.workers.dev
- name: Server 8
  type: vless
  server: 172.67.5.14
  port: 80
  udp: true
  uuid: e993dc08-05f4-48eb-b9ee-bce7aabe1112
  packet-encoding: xudp
  tls: false
  alpn:
  - http/1.1
  network: ws
  ws-opts:
    path: /146.235.18.248:45137
    headers:
      host: cf.bagusfast.workers.dev
- name: Server 9
  type: vless
  server: 104.20.9.155
  port: 80
  udp: true
  uuid: e993dc08-05f4-48eb-b9ee-bce7aabe1112
  packet-encoding: xudp
  tls: false
  alpn:
  - http/1.1
  network: ws
  ws-opts:
    path: /146.235.18.248:45137
    headers:
      host: cf.bagusfast.workers.dev
- name: Server 10
  type: vless
  server: 104.20.10.155
  port: 80
  udp: true
  uuid: e993dc08-05f4-48eb-b9ee-bce7aabe1112
  packet-encoding: xudp
  tls: false
  alpn:
  - http/1.1
  network: ws
  ws-opts:
    path: /146.235.18.248:45137
    headers:
      host: cf.bagusfast.workers.dev
- name: Server 11
  type: vless
  server: 162.159.140.147
  port: 80
  udp: true
  uuid: e993dc08-05f4-48eb-b9ee-bce7aabe1112
  packet-encoding: xudp
  tls: false
  alpn:
  - http/1.1
  network: ws
  ws-opts:
    path: /146.235.18.248:45137
    headers:
      host: cf.bagusfast.workers.dev
- name: Server 12
  type: vless
  server: 172.66.0.145
  port: 80
  udp: true
  uuid: e993dc08-05f4-48eb-b9ee-bce7aabe1112
  packet-encoding: xudp
  tls: false
  alpn:
  - http/1.1
  network: ws
  ws-opts:
    path: /146.235.18.248:45137
    headers:
      host: cf.bagusfast.workers.dev
proxy-groups:
- name: Bagus
  type: select
  proxies:
  - Ping Server
- name: Ping Server
  type: url-test
  url: http://quiz.vidio.com
  interval: 90
  tolerance: 50
  proxies:
  - Server 1
  - Server 2
  - Server 3
  - Server 4
  - Server 5
  - Server 6
  - Server 7
  - Server 8
  - Server 9
  - Server 10
  - Server 11
  - Server 12
rules:
- IP-CIDR,104.17.155.243/32,DIRECT
- IP-CIDR,104.17.156.243/32,DIRECT
- IP-CIDR,104.17.157.243/32,DIRECT
- IP-CIDR,104.17.158.243/32,DIRECT
- IP-CIDR,104.17.159.243/32,DIRECT
- IP-CIDR,104.22.4.240/32,DIRECT
- IP-CIDR,104.22.5.240/32,DIRECT
- IP-CIDR,172.67.5.14/32,DIRECT
- IP-CIDR,104.20.9.155/32,DIRECT
- IP-CIDR,104.20.10.155/32,DIRECT
- IP-CIDR,162.159.140.147/32,DIRECT
- IP-CIDR,172.66.0.145/32,DIRECT
- MATCH,Bagus
